PHP-FFMpeg/PHP-FFMpeg

src/FFMpeg/Filters/Video/CropFilter.php
src/FFMpeg/Filters/Video/VideoFilters.php
tests/FFMpeg/Tests/Filters/Video/CropFilterTest.php

Filter to crop the videos using X,Y `Point`s and W,H `Dimension`s.

Add Crop Filter

---

.github/PULL_REQUEST_TEMPLATE.md

A meaningful pull request template similar to this pull request description.
Such templates should encourage first-timers to create good pull request descriptions, which helps us reviewing it.

Add a meaningful pull request template

---

.github/ISSUE_TEMPLATE.md

A meaningful issue template.
Such templates should encourage first-timers to create good issue descriptions, which helps us reproducing it.

Add a meaningful issue template

---

README.md

| Fixed tickets      | fixes #216
| License            | **MIT**
Added documentation for the watermark filter.

Added documentation for the watermark filter

---

README.md

Fix readme typo to 'explicitly'

---

src/FFMpeg/Filters/Video/VideoFilters.php

| Fixed tickets      | fixes #227
| Related issues/PRs | #227 #268 
Just a method to apply the CustomFilter.
This would allow anyone to apply parameters like '-vf foo bar'.
```php
$video->filters()->custom('my parameters');
```
=> The tests for the filter already exist.

Creation of a method to apply custom filters

---

.gitignore
src/FFMpeg/Filters/Audio/AddMetadataFilter.php
src/FFMpeg/Filters/Video/ExtractMultipleFramesFilter.php
src/FFMpeg/Filters/Video/PadFilter.php
src/FFMpeg/Filters/Waveform/WaveformDownmixFilter.php
src/FFMpeg/Media/Waveform.php

Code improvements. Nothing fancy, just applying recommandations of ttps://insight.sensiolabs.com
To have a bette codebase.

Improvements

---

README.md

| Fixed tickets      | no
| Related issues/PRs | no
Remove not needed spaces in examples

Remove not needed spaces

---

README.md

adding a chapter and making navigating easier
I'd forgotten to update the readme with my latest (approved) pr, so I'm fixing it now.

add missing chapter in readme

---

README.md

Typo in heading
To fix typo in README

typo in heading

---

README.md

| Fixed tickets      | fixes -
| Related issues/PRs | #404 
Fix a typo

fix typo; closes #404

---

README.md

fixes #420
| Fixed tickets      | fixes #420 
| Related issues/PRs | #420 

remove api link

---

README.md

| New feature?       | Yes
| Related issues/PRs | #413 #394  
Added the usage of the API to the README file.

add FFProbe#isValid to readme

---

README.md

add Crop documentation

---

.travis.yml

| Fixed tickets      | fixes #427 
| Related issues/PRs | #427 

speed up travis build

---

.travis.yml

It's useless and it's dying and taking build time :c

drop hhvm support

---

composer.json

add myself to the authors

---

README.md

Add missing require statement.
| Fixed tickets      | fixes #452 
| Related issues/PRs | #452 
Updates README.md.

#452 Update README.md

---

src/FFMpeg/Media/Video.php
tests/Unit/Coordinate/FrameRateTest.php
tests/Unit/FFMpegServiceProviderTest.php
tests/Unit/FFProbe/DataMapping/StreamCollectionTest.php
tests/Unit/FFProbe/DataMapping/StreamTest.php
tests/Unit/FFProbe/OptionsTesterTest.php
tests/Unit/Filters/Audio/AudioClipTest.php
tests/Unit/Filters/Audio/AudioMetadataTest.php
tests/Unit/Filters/Audio/AudioResamplableFilterTest.php
tests/Unit/Filters/FiltersCollectionTest.php
tests/Unit/Filters/Video/CropFilterTest.php
tests/Unit/Filters/Video/CustomFilterTest.php
tests/Unit/Filters/Video/ExtractMultipleFramesFilterTest.php
tests/Unit/Filters/Video/FrameRateFilterTest.php
tests/Unit/Filters/Video/PadFilterTest.php
tests/Unit/Filters/Video/ResizeFilterTest.php
tests/Unit/Filters/Video/RotateFilterTest.php
tests/Unit/Filters/Video/SynchronizeFilterTest.php
tests/Unit/Filters/Video/WatermarkFilterTest.php
tests/Unit/Format/Audio/AudioTestCase.php
tests/Unit/Format/Video/VideoTestCase.php
tests/Unit/Media/AudioTest.php
tests/Unit/Media/ConcatTest.php
tests/Unit/Media/FrameTest.php
tests/Unit/Media/GifTest.php
tests/Unit/Media/VideoTest.php
tests/Unit/Media/WaveformTest.php
tests/Unit/TestCase.php

| BC breaks?         | Yes
| Deprecations?      | Yes
| Fixed tickets      |  #412 
| Related issues/PRs | #412 
Fixed more tests in `PHPUnit 6`, not all.

Fix more tests in PHPUnit 6

---

src/FFMpeg/Media/Video.php
tests/Unit/Coordinate/FrameRateTest.php
tests/Unit/FFMpegServiceProviderTest.php
tests/Unit/FFProbe/DataMapping/StreamCollectionTest.php
tests/Unit/FFProbe/DataMapping/StreamTest.php
tests/Unit/FFProbe/OptionsTesterTest.php
tests/Unit/Filters/Audio/AudioClipTest.php
tests/Unit/Filters/Audio/AudioMetadataTest.php
tests/Unit/Filters/Audio/AudioResamplableFilterTest.php
tests/Unit/Filters/FiltersCollectionTest.php
tests/Unit/Filters/Video/CropFilterTest.php
tests/Unit/Filters/Video/CustomFilterTest.php
tests/Unit/Filters/Video/ExtractMultipleFramesFilterTest.php
tests/Unit/Filters/Video/FrameRateFilterTest.php
tests/Unit/Filters/Video/PadFilterTest.php
tests/Unit/Filters/Video/ResizeFilterTest.php
tests/Unit/Filters/Video/RotateFilterTest.php
tests/Unit/Filters/Video/SynchronizeFilterTest.php
tests/Unit/Filters/Video/WatermarkFilterTest.php
tests/Unit/Format/Audio/AudioTestCase.php
tests/Unit/Format/Video/VideoTestCase.php
tests/Unit/Media/AudioTest.php
tests/Unit/Media/ConcatTest.php
tests/Unit/Media/FrameTest.php
tests/Unit/Media/GifTest.php
tests/Unit/Media/VideoTest.php
tests/Unit/Media/WaveformTest.php
tests/Unit/TestCase.php

Reverts PHP-FFMpeg/PHP-FFMpeg#455
tooo fast

Revert "Fix more tests in PHPUnit 6"

---

tests/Unit/Filters/Audio/AudioImageVideoFilterTest.php

| Fixed tickets      | fixes #524 
| Related issues/PRs | #524 
Fixing the wrong test method that was need to be amended on test case which was merged in #524 
Building the test for the specific image to video conversion

Updating the method name in the test case for image to video conversion pull request

---

README.md

| Fixed tickets      | fixes #547

Document the `setFrameFileType` function

---

.travis.yml
src/FFMpeg/Filters/FiltersCollection.php
tests/Unit/FFProbe/OptionsTesterTest.php

Support, tests and fixes for PHP 8
To add support for PHP 8

PHP 8 Support
