PHP-FFMpeg/PHP-FFMpeg

- src/FFMpeg/Filters/Video/WatermarkFilter.php
The filter does not seem to actually use the watermark (image path). This update fixes the functionality.
> Use watermark image while watermarking!

- composer.json
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | an enhancement
| BC breaks? | no
| Deprecations? | no
| Tests pass? | yes (travis fails because acces denied on http://video-js.zencoder.com/oceans-clip.mp4 probe)
| Fixed tickets | fixes #182 
| License | MIT
The `evenement` lib v2.0 major BC break was the removement of `EventEmitter2` class, which is not used in the `PHP-FFMpeg`. Thus it is possible to require both versions, v1.0 and v2.0 via composer.
Example: Users of lib A which requires `react/socket` which requires `evenement` in v2.0 but also require your `php-ffmpeg/php-ffmpeg` which requires `evenement` in v1.0 have a dependency conflict and have to manually add `"evenement/evenement": "2.0.0 as 1.0.0"` to their projects composer. Because of the v1.0 to v2.0 compatibility this …
> Allow usage of evenement v2.0

- docs/source/API/API/FFMpeg/Format/Video/X264.html
- src/FFMpeg/Format/Video/X264.php
| Related issues/PRs | #250 
This PR adds a method to the Format/Video/X264 class to be able to set the number of passes for this format.
The number of passes may be a potential source of trouble for large files.
> Creation of a setPasses method for the X264 format.

- README.md
The composer.json SHOULD NOT be edited by hand for installation.
Just small change in README.md to use `composer require` for installation.
Because editing the composer.json manually is considered a bad practise.
> Change installation method to composer require

- .gitignore
- README.md
- composer.json
- src/FFMpeg/Filters/Video/PadFilter.php
- src/FFMpeg/Filters/Video/VideoFilters.php
- tests/Unit/Filters/Video/PadFilterTest.php
| Fixed tickets      | fixes #227 
| Related issues/PRs | #227 
This PR contains a new filter which allows the user to resize a video with padding.
This is complementary to the resize filter. You don't have to choose a mode of resize, your video will be resized to fit in the new dimensions, and will be wraps into black bars if the ratio of the new video is not the same of the old one.
This is complementary to the resize filter.
I've created a new filter instead of updating the resize one because the FFMPEG command was way too different for this feature.
It works in the same way than the resize filter.
```php …
```
> Creation of a Pad filter which allows the user to resize his video, using black bars

- README.md
- src/FFMpeg/Filters/Audio/AddMetadataFilter.php
- src/FFMpeg/Filters/Audio/AudioFilters.php
- tests/Unit/Filters/Audio/AudioMetadataTest.php
| Fixed tickets      | fixes #175 #120 
Adds a new Audio Filter. Using ffmpeg -metadata utility we can set metadata values such as title, artist, album etc...
Filter also can add image files to audio files (album artwork)
By not supplying an argument to the filter, it will remove all metadata, including previously set artworks
A simple way to add metadata or album artwork to audio files
```php
$ffmpeg = new FFMpeg\FFMpeg::create();
$audio = $ffmpeg->open($file_path);
$audio->addMetadata([
"title" => "Some Title",
"album" => "Some Album",
"artwork" => "/path/to/some/file.jpg" …
```
> Add audio metadata filter

- README.md
- src/FFMpeg/Filters/Concat/ConcatFilterInterface.php
- src/FFMpeg/Filters/Concat/ConcatFilters.php
- src/FFMpeg/Media/Concat.php
- src/FFMpeg/Media/Video.php
- tests/Unit/Media/ConcatTest.php
- tests/Unit/TestCase.php
- tests/files/concat-list.txt
| Fixed tickets      | fixes #245 
| Related issues/PRs | #245 
This feature allows you to generate one audio or video file, based on multiple sources.
There are two ways to concatenate videos, depending on the codecs of the sources.
If your sources have all been encoded with the same codec, you will want to use the `FFMpeg\Media\Concatenate::saveFromSameCodecs` which has way better performances.
If your sources have been encoded with different codecs, you will want to use the `FFMpeg\Media\Concatenate::saveFromDifferentCodecs`.
The first function will use the initial codec as the one for the generated file. …
> Concatenation feature

- src/FFMpeg/Media/Frame.php
- tests/Unit/Media/FrameTest.php
| Fixed tickets      | 
| Related issues/PRs | 
For now, when we are generating thumbnails, we are forced to save the thumbnail on the disk. This can be very time consuming in some cases.
My method allow us to retrieve directly base 64 encoded image as a string, so you can embed it into an html <img /> tag or whatever
I had the issue, I am generating a thumbnail to display on a page and I didn't want to save it in a temporary file that would be deleted each time user navigate on a new video
```
echo "<img src='data:images/png;base64," . getThumbnail("/home/guillaume/Vidéos/Seigneur des anneaux/01_La …
```
> Added a getAsBase64() method to Frame object

- README.md
Fix documentation class namespace.
> Fix Format classes namespace in README

- src/FFMpeg/Coordinate/TimeCode.php
- src/FFMpeg/Filters/Audio/AddMetadataFilter.php
- src/FFMpeg/Filters/Audio/AudioClipFilter.php
- src/FFMpeg/Filters/Audio/AudioFilters.php
- src/FFMpeg/Filters/Audio/SimpleFilter.php
- tests/Unit/Filters/Audio/AudioClipTest.php
| New feature?       |Yes
| Fixed tickets      | 
| Related issues/PRs | #240 
Adds the ability to clip an audio.
Which problem does the PR fix?
```php
$audio = $ffmpeg->open('audio.mp3');
// Now we can do
$audio->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(0), FFMpeg\Coordinate\TimeCode::fromSeconds(60));
```
I really want to thank @swordsreversed, since he's the person who gave us the foundation, I could build with.
Additionally, I've added 2 methods to TimeCode, because I thought I need to validate first, wether the second value given is bigger than the first. (...) But I think these methods could be useful in the …
> Audio Clip

- src/FFMpeg/Filters/Video/ExtractMultipleFramesFilter.php
| Fixed tickets      | fixes #333 
| Related issues/PRs | #333
A fix to the issue 333.
We set a default duration variable to 0 in the ExtractMultipleFramesFilter.php.
It generated an exception in some cases.
> Set a default duration to 0 to fix issue 333

- src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php
| Fixed tickets      | fixes #339 
| Related issues/PRs | #339 
This PR changes the way we use the variable currentSize in AbstractProgressListener.php. We first check to see if it's an integer. If not, we convert it.
With PHP7, when this variable was not a numeric value, an error was thrown.
> The variable currentSize in AbstractProgressListener.php MUST be an integer. Test it and convert it if needed.

- src/FFMpeg/Filters/Audio/AddMetadataFilter.php
- tests/Unit/Filters/Audio/AudioMetadataTest.php
| Related issues/PRs | #281 
This commit fixes this issue by copying (by value) the `metaArr`
property to a local variable each time the filter is applied.
When the `AddMetadataFilter` is applied on an `Audio` media, the `artwork`
parameter was being unset from the `metaArr` array.
Saving the same `Audio` instance multiple times generated the
correct commands for the first export, but the subsequent commands were
missing the `artwork` parameter.
```php
$ffmpeg = new FFMpeg\FFMpeg::create();
$audio = $ffmpeg->open('track.wav');
$audio->addMetadata([
"title" => "Some Title",
"album" => …
```
> Fix missing audio artwork metadata on multiple exports

- src/FFMpeg/Filters/Video/ResizeFilter.php
- src/FFMpeg/Media/Video.php
- tests/Unit/Filters/Video/ResizeFilterTest.php
| Related issues/PRs | #308
Support resize and watermark in ordering.
Cannot resize image then adding watermark. The ordering is ignored.
The following codes will have different results.
```php
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open($filepath);
$filters = $video->filters();
$filters->resize(new FFMpeg\Coordinate\Dimension($width, $height), FFMpeg\Filters\Video\ResizeFilter::RESIZEMODE_SCALE_HEIGHT, false);
$filters->watermark($watermarkPath, array(
'position' => 'relative',
'bottom' => 0,
'left' => 0,
));
$video->save(new FFMpeg\Format\Video\X264(), …
```
> Support resize and watermark in ordering.

- src/FFMpeg/Coordinate/Point.php
- tests/Unit/Coordinate/PointTest.php
Support crop video with dynamic point
for example 
```
ffmpeg -i input.mp4 -filter:v "crop=in_w/4:in_h:t*100:0" output.mp4
```
for creating a motion animation from a video, something like dynamic view of a video
```php
require __DIR__."/../vendor/autoload.php";
try {
$ffmpeg = \FFMpeg\FFMpeg::create();
$video = $ffmpeg->open(__DIR__."/merge_img.mp4");
$video
->filters()
->crop(new \FFMpeg\Coordinate\Point("t*100", 0, true), new \FFMpeg\Coordinate\Dimension(200, 600));
$video->save(new \FFMpeg\Format\Video\X264(), __DIR__."/test.mp4"); …
```
> support crop with dynamic point

- src/FFMpeg/FFProbe.php
- tests/Functional/FFProbeTest.php
| New feature?       | Yes
| Fixed tickets      | fixes #394 
Makes it possible to validate media using ffmpeg
It's always good to know what you're going to do.
```php
$ffprobe = FFProbe::create();
// now we can do
$ffprobe->isValid(__DIR__ . '/../files/WrongFile.mp4');
```
> Add FFProbe#isValid

- src/FFMpeg/Media/Video.php
| Fixed tickets      | N/A
| Related issues/PRs | N/A
A very small fix to convert the use of [] into array()
The use of [] prevented PHP 5.3 compatibility.  Fixed that.
> Fixed: the use of [] was killing PHP 5.3 compat

- src/FFMpeg/Media/Audio.php
- src/FFMpeg/Media/Video.php
| New feature?       | Yes
| Fixed tickets      | fixes #403 
| Related issues/PRs | #403
The possibility of getting the command that would be executed.
It's useful for debugging purposes. It is intended to not document the function itself, but only use it for debugging purposes.
None.
> add `getFinalCommand`

- .gitignore
- README.md
- src/FFMpeg/Media/Audio.php
- src/FFMpeg/Media/Waveform.php
- tests/Unit/Media/WaveformTest.php
Added the ability to define color palette for the waveform. The default color is black.
By default ffmpeg uses a mixture of colors (mostly orange) that result in an image that is very difficult for post-processing and downright ugly.
```php
$audio->waveform(1280, 200, ['#00FF00']);
//or
$waveform = $audio->waveform(1280, 200);
$waveform->setColors(['#FFFFFF']);
~~~
> Added color option to waveform generation

- composer.json
- tests/Functional/FunctionalTestCase.php
- tests/Unit/FFMpegServiceProviderTest.php
- tests/Unit/TestCase.php
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
Just needed to bump PHPUnit version to [`4.8.36`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4836---2017-06-21), to keep compatibility.
> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

- src/FFMpeg/Media/Video.php
- tests/Unit/Filters/Audio/AudioClipTest.php
- tests/Unit/Filters/Audio/AudioMetadataTest.php
- tests/Unit/Filters/Audio/AudioResamplableFilterTest.php
- tests/Unit/Filters/FiltersCollectionTest.php
- tests/Unit/Filters/Video/CropFilterTest.php
- tests/Unit/Filters/Video/CustomFilterTest.php
- tests/Unit/Filters/Video/ExtractMultipleFramesFilterTest.php
- tests/Unit/Filters/Video/FrameRateFilterTest.php
- tests/Unit/Filters/Video/PadFilterTest.php
- tests/Unit/Filters/Video/ResizeFilterTest.php
- tests/Unit/Filters/Video/RotateFilterTest.php
- tests/Unit/Filters/Video/SynchronizeFilterTest.php
- tests/Unit/Filters/Video/WatermarkFilterTest.php
- tests/Unit/Format/Audio/AudioTestCase.php
- tests/Unit/Format/Video/VideoTestCase.php
- tests/Unit/Media/AudioTest.php
- tests/Unit/Media/ConcatTest.php
- tests/Unit/Media/FrameTest.php
- tests/Unit/Media/GifTest.php
- tests/Unit/Media/VideoTest.php
- tests/Unit/Media/WaveformTest.php
- tests/Unit/TestCase.php
| BC breaks?         | Yes
| Deprecations?      | Yes
| Fixed tickets      | #412 
| Related issues/PRs | #412 #455 
As suggested in #455, let's fix the tests step by step. First:
- Use a fluent interface when defining `Mocks`. This fix tests `Call to undefined method getMock()`.
> Use fluent interface when defining mocks

- tests/Unit/FFMpegServiceProviderTest.php
- tests/Unit/Media/AudioTest.php
- tests/Unit/Media/VideoTest.php
| BC breaks?         | Yes
| Deprecations?      | Yes
| Fixed tickets      | #412 
| Related issues/PRs | #412 #455 #458 
As suggested in #455, let's fix the tests step by step. Second:
- Use `expectException` and `expectExceptionMessage` instead of `setExpectedException`, as it doesn't exist in `PHPUnit 6` anymore.
> Fix Expect Exception tests

- composer.json
| Related issues/PRs | #470
use official version of *neutron/temporary-filesystem* in `composer.json`
the dependency problems have been resolved in [version 2.3.0](https://github.com/romainneutron/Temporary-Filesystem/commits/2.3.0).
> use official version of neutron/temporary-filesystem

- src/FFMpeg/Format/Audio/DefaultAudio.php
- src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php
- src/FFMpeg/Format/ProgressableInterface.php
- src/FFMpeg/Format/Video/DefaultVideo.php
- src/FFMpeg/Media/Audio.php
- src/FFMpeg/Media/Video.php
- tests/Unit/Format/ProgressListener/VideoProgressListenerTest.php
When you clipping video, the progress showing wrong info. Showing the info like you transcoding the source video instead of clipping video part you trying to  transcode.
On the class [AbstractProgressListener](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/FFMpeg/Format/ProgressListner/AbstractProgressListener.php) **initialize** function (line 258), the duration for compaction  is getting from the source video instead of the clipping video.
```php
require_once( dirname(__DIR__) . "/vendor/autoload.php");
$ffmpeg = …
```
> Fix Clipping video transcoding progress not correct

- src/FFMpeg/Format/Audio/DefaultAudio.php
- src/FFMpeg/Format/Video/DefaultVideo.php
| Fixed tickets      | fixes #484 
| Related issues/PRs | #484 
I forgot to change the Default Media classes the createProgressListener function.
> Fix Clipping video transcoding progress not correct #2

- src/FFMpeg/Filters/Video/ExtractMultipleFramesFilter.php
- tests/Unit/Filters/Video/ExtractMultipleFramesFilterTest.php
| Fixed tickets      | fixes # 
| Related issues/PRs | #493 
Explain the contents of the PR.
When using ExtractMultipleFramesFilter, it would be nice to choose the file type of the frame image e.g jpg, png, etc.. 
Which problem does the PR fix?
It might be better to create frames with png than with jpg: 
https://twitter.com/FFmpeg/status/970382979280154624
```php
$frameFileType = 'jpg';
$filter = new ExtractMultipleFramesFilter($frameRate, $destinationFolder);
$filter->setFrameFileType($frameFileType);
```
> allow to set frame file type instead of hardcoded jpg

- src/FFMpeg/Media/Frame.php
- tests/Unit/Media/FrameTest.php
| Fixed tickets      | fixes #532
| Related issues/PRs | #532
fix a bug in src/FFMpeg/Media/Frame.php when calling Frame->save()，Add a judgment when the $pathfile be spliced
> fix a bug when calling Frame->save()

- README.md
- src/FFMpeg/Media/AbstractVideo.php
- src/FFMpeg/Media/Clip.php
- src/FFMpeg/Media/Video.php
- tests/Unit/Media/ClipTest.php
Cutting video with clip filter is slow because use output seeking method. 
This PR add clip that use input seeking method. It is faster option. For more information see http://trac.ffmpeg.org/wiki/Seeking
Because cut filter is slow. 
```php
$clip = $video->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(30), FFMpeg\Coordinate\TimeCode::fromSeconds(15));
$clip->save(new FFMpeg\Format\Video\X264(), 'video.avi');
```
On clip you can apply same filters as on video. For example resizing filter.
```php
$clip = …
```
> Clip using input seek

- composer.json
alchemy/binary-driver 2 added support for Symfony4. So I want to check if this library (latest version) works out of the box with that version
> Adds Symfony 4 support

- src/FFMpeg/Media/AbstractVideo.php
| Related issues/PRs | #570 
Add missing typehint to FFMpeg/Media/AbstractVideo
Parent class's methods has different signature.
in parrent:
FFMpeg\Media\Audio has
- getFinalCommand(FormatInterface $format, string $outputPathfile)
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/dd47d409667621230a49205acde029a1df9561dd/src/FFMpeg/Media/Audio.php#L90
- buildCommand(FormatInterface $format, string $outputPathfile)
https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/dd47d409667621230a49205acde029a1df9561dd/src/FFMpeg/Media/Audio.php#L103
FFMpeg\Media\AbstractVideo has
- getFinalCommand(FormatInterface $format, …
> Add missin typehint to FFMpeg/Media/AbstractVideo

- composer.json
| Fixed tickets      | N/A
| Related issues/PRs | N/A
I add the latest BinaryDriver version constraint as it seems there was an issue with tags v2.0.0, v4.1,...
You can have a look at https://github.com/alchemy-fr/BinaryDriver/issues/25
> Add compatibility to the latest BinaryDriver version

- src/FFMpeg/Media/Concat.php
| BC breaks?         |  if someone did a workaround themselves
The [concatenation](https://github.com/PHP-FFMpeg/PHP-FFMpeg#concatenation) does not work if there is a space or \ (backslash) in one of the source file paths. (In windows its very likely that there is a \ in the path, so for me the concatenation did not work)
adds \ before the characters ', ", \, SPACE and NUL
related ffmpeg docs: https://ffmpeg.org/ffmpeg-formats.html#concat
> Path to a file to read; special characters and spaces must be escaped with backslash or single quotes. 
example of the temp file before the code change (which did not work)
```
file …
```
> concat allow special chars in filename

- src/FFMpeg/Media/AbstractVideo.php
| Fixed tickets      | n/a
| Related issues/PRs | n/a
This fixes an edge case where php with the simple equal operator (==) considers  0 and "-vf" as equal
Out of bounds array access/attempted merging of arguments that are not filters
n/a
> Strict comparison for -vf check

- src/FFMpeg/Filters/Frame/CustomFrameFilter.php
- src/FFMpeg/Filters/Frame/FrameFilters.php
- tests/Unit/Filters/Frame/CustomFrameFilterTest.php
| Fixed tickets      | fixes #610 
| Related issues/PRs | #610 
This adds a custom filter to frame
E.g. it's possible to create image tiles from a video, see example code.
```php
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open('/some/video.mp4');
$video->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(0))
->addFilter(new CustomFrameFilter('scale=142:80,fps=1,tile=10x10:margin=2:padding=2'))
->save('/some/picture.jpg');
> added custom frame filter

- src/FFMpeg/Filters/Audio/AudioFilters.php
- src/FFMpeg/Filters/Audio/CustomFilter.php
- tests/Unit/Filters/Audio/CustomFilterTest.php
… available for Video
| Fixed tickets      | N/A
| Related issues/PRs | N/A
Added custom filters for Audio, in the same way as custom filters are available for Video.
Allows custom filters to be used for Audio.
$audio->filters()->custom('loudnorm=I=-13');
Added relevant Unit Tests
> Added custom filters for Audio, in the same way as custom filters are available for Video

- src/FFMpeg/Format/Video/WebM.php
- src/FFMpeg/Format/Video/X264.php
| Fixed tickets      | fixes #645 
| Related issues/PRs | #645 
Allows to pass 'copy' as audio codec for X264 and WebM Video Formats
Allowing to pass 'copy' as audio codec is very useful when you don't need/care about an specific audio codec and you just want to use the same original codec. This also avoids re-encoding the audio, thus making the transcode process faster.
This PR just adds 'copy' as an available audio codecs for both formats, so there are not breaking changes and neither new tests because there are alredy tests for getAvailableCodecs.
```php
$format = new X264('copy');
$format->save();
```
> Add copy as available codecs for X264 and WebM

- README.md
- src/FFMpeg/Format/Video/DefaultVideo.php
- src/FFMpeg/Format/VideoInterface.php
- src/FFMpeg/Media/AbstractVideo.php
- src/FFMpeg/Media/Clip.php
- tests/Unit/Format/Video/InitialParametersTest.php
| Related issues/PRs | #625, #675
This is a similar method to setAdditionalParamaters. It allows you to instead set an array of 'initial' parameters that are added before the input file. I needed this mainly because I'm recording realtime video in OPUS and transcoding the audio for playback to AAC. An ffmpeg build with libopus requires you to pass '-acodec libopus' otherwise it defaults to the default opus codec which doesn't work very well.
It's fairly common when using the newer proprietary codecs to require this ability.
This fixes not being able to pass initial …
> Added initial parameters

- README.md
| Fixed tickets      | none
| Related issues/PRs | none
Simple typo fix, the readme is referring to the incorrectly cased version of the class.
Documentation
```php
use FFMpeg\Coordinate\FrameRate;
```
None
None
> Fixed typo in the readme referring to FrameRate

- .travis.yml
- composer.json
| Fixed tickets      | fixes -
Update add tests again PHP 8.
That the package can be install for newer php versions.
Install PHP 8 / Nightly and use PHP.
> Add Support for PHP 8

- composer.json
| Related issues/PRs | https://github.com/romainneutron/Temporary-Filesystem/pull/16, #747
Allow newer version of temporary filesystem.
Allow version which is compatible to php 8.
No BC Break.
> Allow newer version of temporary filesystem for php 8 support

- src/FFMpeg/Coordinate/AspectRatio.php
- src/FFMpeg/FFProbe/DataMapping/AbstractData.php
- src/FFMpeg/FFProbe/DataMapping/Stream.php
- src/FFMpeg/FFProbe/OptionsTester.php
- src/FFMpeg/FFProbe/OptionsTesterInterface.php
- src/FFMpeg/Filters/Video/ResizeFilter.php
- src/FFMpeg/Filters/Video/VideoFilters.php
- src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php
- src/FFMpeg/Format/VideoInterface.php
- src/FFMpeg/Media/Frame.php
| Bug fix?           | kind of, but no
| Fixed tickets      | none
| Related issues/PRs | none
Some docblocks use Boolean as a type even though it should be `bool` and not an instance of Boolean class. This PR fixes this
I am fixing this because Psalm complains about an unknown type when using methods with this type:
```
ERROR: UndefinedDocblockClass - [...].php:37:14 - Docblock-defined class or interface FFMpeg\FFProbe\DataMapping\Boolean does not exist (see https://psalm.dev/200)
if (!$format->has('duration')) {
```
> Fix boolean types

- src/FFMpeg/Coordinate/Dimension.php
- src/FFMpeg/Coordinate/Point.php
- src/FFMpeg/Filters/AdvancedMedia/ComplexFilterContainer.php
- src/FFMpeg/Filters/Audio/AudioResamplableFilter.php
- src/FFMpeg/Filters/Audio/CustomFilter.php
- src/FFMpeg/Filters/FilterInterface.php
- src/FFMpeg/Filters/Frame/CustomFrameFilter.php
- src/FFMpeg/Filters/Frame/DisplayRatioFixerFilter.php
- src/FFMpeg/Filters/Video/ClipFilter.php
- src/FFMpeg/Filters/Video/CropFilter.php
- src/FFMpeg/Filters/Video/CustomFilter.php
- src/FFMpeg/Filters/Video/PadFilter.php
- src/FFMpeg/Filters/Video/ResizeFilter.php
- src/FFMpeg/Filters/Video/RotateFilter.php
- src/FFMpeg/Filters/Video/WatermarkFilter.php
- src/FFMpeg/Filters/Waveform/WaveformDownmixFilter.php
- src/FFMpeg/Format/Audio/DefaultAudio.php
- src/FFMpeg/Format/AudioInterface.php
- src/FFMpeg/Format/FormatInterface.php
- src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php
- src/FFMpeg/Format/Video/DefaultVideo.php
- src/FFMpeg/Format/Video/X264.php
- src/FFMpeg/Format/VideoInterface.php
- src/FFMpeg/Media/Audio.php
- src/FFMpeg/Media/Clip.php
- src/FFMpeg/Media/Concat.php
- src/FFMpeg/Media/Frame.php
- src/FFMpeg/Media/Gif.php
- src/FFMpeg/Media/Video.php
*This is a replacement for [an older PR](#776).*
| Fixed tickets      | fixes #774
Fixes all the errors reported when running the `generate-docs.sh` script. No code changes, only comments.
Standardises all `integer` and `boolean` type designators to unaliased `int` and `bool`, as per [PSR-12 section 2.5](https://www.php-fig.org/psr/psr-12/#25-keywords-and-types).
> Fix docs generation, PSR-12 type compliance

- .gitattributes
| Fixed tickets      | #710
| Related issues/PRs | #706 
the `tests` directory as well as `phpunit.xml.dist` and `travis.yml` files are no longer included in an archive of the project.
As explained in [this](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/) post, there is no need for developer oriented files within vendor folder in a another project. The author argues that this can speed up deployments.
Issuing the command:
```bash
composer require php-ffmpeg/php-ffmpeg --prefer-dist
```
should no longer include files that only concern developers of the library.
Thanks …
> composer ... --prefer-dist now ignores dev files

- README.md
- src/FFMpeg/Format/Video/DefaultVideo.php
- src/FFMpeg/Format/Video/X264.php
- src/FFMpeg/Media/AbstractVideo.php
- tests/Functional/AudioConcatenationTest.php
- tests/Unit/Format/Video/VideoTestCase.php
- tests/Unit/Media/VideoTest.php
| Fixed tickets      | fixes #418 
| Related issues/PRs | #418
By passing `0` to `setKiloBitrate()` we can bypass setting `-b:v` setting.
Sometimes we may prefer not to use `-b:v` in favor to `crf`.
No BC breaks.
> Add ability to disable -b:v

- README.md
- composer.json
- src/FFMpeg/FFMpegServiceProvider.php
- tests/Unit/FFMpegServiceProviderTest.php
| Deprecations?      | yes
Remove Silex support.
Silex was abandoned 3 years ago, removing its support will allow to bump some dependencies.
- `FFMpeg\FFMpegServiceProvider` was deprecated, the user must implement the provider by itself.
> Remove silex support

- CHANGELOG.md
- README.md
- composer.json
- src/FFMpeg/Media/AbstractMediaType.php
- src/FFMpeg/Media/AbstractVideo.php
- src/FFMpeg/Media/Concat.php
- tests/FFMpeg/Unit/Media/AdvancedMediaTest.php
- tests/FFMpeg/Unit/Media/ConcatTest.php
- tests/FFMpeg/Unit/Media/VideoTest.php
| Related issues/PRs | #853
- Added configuration key to customize the temporary directory used for passes.
- Fix for the path of the default `ffmpeg-passes*` temporary directory.
> Specify temporary directory + fix for default `ffmpeg-passes*` temporary directory

- .github/workflows/test.yaml
- composer.json
This expands the library's stated PHP support to include PHP 8.3 and the 7.x branch of Symfony. I've tested both locally and the full phpunit suite passes without issue using both.
> Update dependencies to include PHP 8.3 and Symfony 7.x.

- src/Alchemy/BinaryDriver/AbstractBinary.php
- src/Alchemy/BinaryDriver/BinaryInterface.php
- src/Alchemy/BinaryDriver/Listeners/Listeners.php
- src/Alchemy/BinaryDriver/ProcessRunner.php
- src/FFMpeg/Driver/FFMpegDriver.php
- src/FFMpeg/Driver/FFProbeDriver.php
- src/FFMpeg/FFMpeg.php
- src/FFMpeg/FFProbe.php
- src/FFMpeg/Filters/Audio/AudioClipFilter.php
- src/FFMpeg/Filters/Video/ClipFilter.php
- src/FFMpeg/Media/Clip.php
- src/FFMpeg/Media/Video.php
| Deprecations?      | yes
| Fixed tickets      | 
| Related issues/PRs | #933
This PR changes the implicitly marked nullable parameters in functions to explicitly marked ones
This fixes deprecation warnings when using php8.4
Example:
`FFMpeg\FFProbe::create(): Implicitly marking parameter $logger as nullable is deprecated, the explicit nullable type must be used instead in /xx/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php on line 214`
> Fix php8.4 deprecated implicitly marking parameter as nullable

- src/FFMpeg/Driver/FFMpegDriver.php
- src/FFMpeg/Driver/FFProbeDriver.php
| Related issues/PRs | https://github.com/symfony/symfony/pull/59042#issuecomment-2580399840
I implemented a video Symfony validator [in this PR](https://github.com/symfony/symfony/pull/59042).
The validator is using FFMpeg to get some details by the video file.
When we run the PHPUnit tests, we have [this notice](https://github.com/symfony/symfony/actions/runs/12697124617/job/35392688394?pr=59042#step:10:3207).
This PR is trying to fix the notice by setting the return type declaration defined by [the abstract method `AbstractBinary::getName()`](https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/master/src/Alchemy …
> Fix getName() native return type declaration

- .github/workflows/test.yaml
- src/Alchemy/BinaryDriver/Configuration.php
- src/Alchemy/BinaryDriver/ConfigurationInterface.php
| Fixed tickets      | fixes #875
| Related issues/PRs | #875
Fix compatiblity with ArrayAccess
Return type of Alchemy\BinaryDriver\Configuration::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool
> Fix type declaration
